version: '3.7'

services:
  ingest:
    build:
        context: .
        dockerfile: ./Dockerfile
    env_file: .env.dev
    volumes:
        - .:/home/node/tft-match-fetcher
    command: npm run start
    depends_on:
        - postgres
        - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    sysctls:
        - net.core.somaxconn=511
  postgres:
    image: postgres:13-alpine
    env_file: database/db.env
    volumes:
      - ./database/data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
