version: '3.7'

services:
  ingest:
    build:
        context: .
        dockerfile: ./Dockerfile
    env_file: .env
    depends_on:
        - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    sysctls:
        - net.core.somaxconn=511
