version: '3.7'

services:
  ingest:
    build:
        context: .
        dockerfile: ./Dockerfile
    env_file: .env
    depends_on:
        - redis
  redis:
    image: redis:alpine
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    sysctls:
        - net.core.somaxconn=511
